# Generated by Django 3.2.16 on 2024-06-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='аbout',
            field=models.TextField(blank=True, verbose_name='О пользователе'),
        ),
    ]
