# Generated by Django 3.2.16 on 2024-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_аbout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='аbout',
            field=models.TextField(blank=True, null=True, verbose_name='О пользователе'),
        ),
    ]
