# Generated by Django 3.2.16 on 2024-06-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_аbout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='аbout',
            new_name='info',
        ),
    ]
