# Generated by Django 3.2.16 on 2024-06-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_аbout_myuser_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
